project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

website:
  title: "goodwave"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: lumen
      dark: darkly
    css: styles.css

editor: visual

